### ISSUE TITLE
Get displayed months on multiple years

### ISSUE THREAD

**Issue by MasterCynder** [adamstyrc/calendarro#14]
Hello,
Thanks for your work !
When I use startDate for a year and a endDate to year+1 (or more), I can't display months of the next year.

**Comment by parth22** [comment]
Hello, @MasterCynder how you apply start and end date?

**Comment by MasterCynder** [comment]
Calendarro(
   displayMode: DisplayMode.MONTHS,
   startDate: DateTime.now(),
   endDate: DateTime(2020, 12, 31),
)

I can slide to the last month of this year but, I can't slide beyond.

**Comment by adamstyrc** [comment]
Hey @MasterCynder I just checked it. 
Yes, it's a bug. I'll fix in this weekend I hope :) 

Stay tuned!

**Comment by adamstyrc** [comment]
@MasterCynder 
Actually the fix was quite easy so I just uploaded v1.1.1 !
Let me know if all works! :)

**Comment by MasterCynder** [comment]
Everything is okay. Thank you very much !
