### ISSUE TITLE
Set selecting limite.

### ISSUE THREAD

**Issue by aminejaf** [adamstyrc/calendarro#2]
Hi, first of all i want to say thanks for this awsome package.

• I was wondring and trying to set a **limite** for selected dates ( by default you can select more than 5++) but i want to stop the select in the UI once the user has selected 5 days.

• And please how can i set the " **endDate** " to **current day**.

Thanks.

**Comment by adamstyrc** [comment]
Hey,
I'm very sorry for long response :( I was out of the project.

1. 

> I was wondring and trying to set a limite for selected dates ( by default you can select more than 5++) but i want to stop the select in the UI once the user has selected 5 days.

Currently if you want to implement a limit for selecting date you would have to implement your own 
**DayTileBuilder** . Please look into **DefaultDayTileBuilder** and **CalendarroDayItem** . You could prepare similar method to CalendarroDayItem.handleTap() but with check on the limitation you want using calendarroState.selectedDates.size .
Then pass your DayTileBuilder in Calendarro constructor field :) 

Maybe I will add your idea to v0.0.5 but there is no specific plan for release yet ;)

2. 

> • And please how can i set the " endDate " to current day.
e.g.
`Calendarro(endDate: DateTime.now())`
:)
