### ISSUE TITLE
Show Month and Year

### ISSUE THREAD

**Issue by mesl1012** [adamstyrc/calendarro#22]
hello @adamstyrc 
Is it possible to show the Month and Year and change it?

**Comment by SebastienBtr** [comment]
There is a callback that you can use when you are in MONTHS display mode, and you can update a variable to show the current month and year:

```
onPageSelected: (DateTime start, DateTime end) {
    setState(() {
        currentMonth = DateFormat('yMMMM').format(start);
    });
 },
```

**Comment by PrakashNaidu2662** [comment]
Hello @SebastienBtr
 
`DateFormat('yMMMM').format(start);`

Do we need to create a class "DateFormat" for the above piece of code?

**Comment by SebastienBtr** [comment]
Hi,
no you don't, this is native: https://api.flutter.dev/flutter/intl/DateFormat-class.html
you have to import `package:intl/intl.dart`
sorry for the late answer

**Comment by adamstyrc** [comment]
@SebastienBtr answer is correct :)
