### ISSUE TITLE
Feature request: Add a range selectionMode

### ISSUE THREAD

**Issue by SebastienBtr** [adamstyrc/calendarro#25]
Having a range selection mode would be really nice, example: https://pub.dev/packages/date_range_picker

**Comment by adamstyrc** [comment]
Hey @SebastienBtr :)

 I see this topic quite late  :( but I like the idea! I'll work on it this week :)

**Comment by adamstyrc** [comment]
@SebastienBtr 

Just shipped Calendarro 1.20. It has a new `SelectionMode.RANGE` so selecting will work just as you showed in https://pub.dev/packages/date_range_picker . 

You will have to set custom `dayTileBuilder` field to display it like in the link, but all is possible :)
