### ISSUE TITLE
selected dates does not get update when you unselect a date from list of dates

### ISSUE THREAD

**Issue by AbdulBasitSaleem** [adamstyrc/calendarro#28]
Hi @adamstyrc 

I have a list of dates as selected dates, when user unselect one of them, then it should update the UI that one date is removed from list.

Need help ASAP.

Regards

**Comment by AbdulBasitSaleem** [comment]
Hi! @adamstyrc @SwissCheese5

return Calendarro(
startDate: startDate,
endDate: endDate,
displayMode: DisplayMode.WEEKS,
selectionMode: SelectionMode.MULTI,
selectedDates: listOfDates,
onPageSelected: (DateTime datetime1, DateTime dateTime2) {
},
onTap: (date) {
if (!listOfDates.contains(date)) {
listOfDates.add(date);
} else {
listOfDates.remove(date);
}

    setState(() {
    });
  },
);
List of dates does not get update, Can you please help me regarding this?

**Comment by adamstyrc** [comment]
Hey @AbdulBasitSaleem 

If in onTap you will invoke `calendarro.selectedDates` you will get a list with all currently selected dates (**before the tap happened**).
Maybe just read it instead of adding a custom `listOfDates`

Also, I use `DateUtils.isSameDay()` instead of `contains()` to check if the date is already added ;)

**Comment by AbdulBasitSaleem** [comment]
Thanks @adamstyrc  for you kind reply. It would be more helpful, if you can provide me the code snippet

Regards

**Comment by adamstyrc** [comment]
In onTap:
'''
listOfDates.clear()
listOfDates.addAll(calendarro.selectedDates)
listOfDates.add(date)
'''

**Comment by AbdulBasitSaleem** [comment]
do, I have to declare Calendarro calendarro = Calendarro() first to access calendarror.selectedDates in the class?

**Comment by adamstyrc** [comment]
@AbdulBasitSaleem Sure

> do, I have to declare Calendarro calendarro = Calendarro() first to access calendarror.selectedDates in the class?

sure, you have to.

I close the topic as it's more programming question than how Calendarro works ;)

**Comment by AbdulBasitSaleem** [comment]
@adamstyrc 
I tried this way, It gets unselect when you tap twice on a date and sometime it makes a data selected which is unselected.

Calendarro(
      startDate: startDate,
      endDate: endDate,
      displayMode: DisplayMode.WEEKS,
      selectionMode: SelectionMode.MULTI,
      selectedDates: calendaro.selectedDates,
      onTap: (date) {
        if (!listOfDates.contains(date)) {
          listOfDates.add(date);
        } else {
          listOfDates.remove(date);
        }

        calendaro.selectedDates.clear();
        calendaro.selectedDates.addAll(listOfDates);

        setState(() {

        });
      },
    );

**Comment by UjjawalPanchal** [comment]
> @adamstyrc
> I tried this way, It gets unselect when you tap twice on a date and sometime it makes a data selected which is unselected.
> 
> Calendarro(
> startDate: startDate,
> endDate: endDate,
> displayMode: DisplayMode.WEEKS,
> selectionMode: SelectionMode.MULTI,
> selectedDates: calendaro.selectedDates,
> onTap: (date) {
> if (!listOfDates.contains(date)) {
> listOfDates.add(date);
> } else {
> listOfDates.remove(date);
> }
> 
> ```
>     calendaro.selectedDates.clear();
>     calendaro.selectedDates.addAll(listOfDates);
> 
>     setState(() {
> 
>     });
>   },
> );
> ```

Hi could you please share the code snippet how you initialize the Calendarro...?
