### ISSUE TITLE
Widget height exceeds visible region

### ISSUE THREAD

**Issue by SwissCheese5** [adamstyrc/calendarro#3]
![2019-08-05_17-05-37](https://user-images.githubusercontent.com/7407478/62470542-567b8a80-b7a3-11e9-9d42-4c3600fb89c3.gif)
The widget goes beyond the calender days and it cant be shrunken down or clipped.

**Comment by SwissCheese5** [comment]
https://github.com/adamstyrc/calendarro/blob/master/lib/calendarro_page.dart#L8
I believe this is the cause, it tries to do 6 rows regardless.

**Comment by adamstyrc** [comment]
Hey!

Thanks for reporting that issue. Calendarro was projected this way as it
could turn out the further you move month by month finally there could be 6
rows. Maybe using

>  displayMode: DisplayMode.WEEKS

would be enough? Or do you still need your Calendarro height to be as small
as possible?

**Comment by SwissCheese5** [comment]
It needs to be small. What month could possible produce 6 rows?

The reason it has to be small is so we can realistically lay out elements in a practical manner without dead and wasted screen realestate.

IMO: Add a boolean, when true it would dynamically resize to the current month, otherwise it would have this size. And perhaps allow clipping/resizing behavior.

**Comment by adamstyrc** [comment]
Well, if e.g. 1 day of a month is Sunday then you can likely have 6 rows of
weeks.
Alright, I'll try to add that functionality. Feel free also to make a pull
request with solution if you like :)
For now you could use Stack layout to e.g. put the button after 3 row
anyways if you're sure it will not exceed.

**Comment by SwissCheese5** [comment]
I'm happy to hear that you will work on this! I don't wish to use a Stack layout because a dynamicall resizing calender is actually pretty useful for layout.

Also, one more thing: There is no page indicator. Might make a separate issue about that

**Comment by adamstyrc** [comment]
Alright! :)

Page indicator can be done separately. E.g. in my own app I added arrows on
left and right.
I didn't plan to make it as a part of Calendarro.

**Comment by adamstyrc** [comment]
Hey @SwissCheese5 

I'm happy to announce **version 1.0.0** as just been shipped!
The Calendarro height is now calculated and adjusted to pages content. 

If you only have e.g. 1 month with 2 rows, it will adjust height to these 2 rows.
If you have 2 pages: 2 rows and 5 rows, it will adjust height to 5 rows as it's max :)

Thank you for reporting, cheers! #5
