### ISSUE TITLE
Selected dates reset between months

### ISSUE THREAD

**Issue by SwissCheese5** [adamstyrc/calendarro#4]
![2019-08-07_17-56-16](https://user-images.githubusercontent.com/7407478/62633368-ae012e00-b93c-11e9-8ee2-1f57aee826c2.gif)

**Comment by adamstyrc** [comment]
Hi! 

I cannot observe this case, could you pass what exact dates your calendar is set to ?

**Also mind:**
 if you've created your own **dayTileBuilder** the item you build it with has to create selection ui by it's own. You could get it with
_calendarroState.isDateSelected(date);_

See     https://github.com/adamstyrc/calendarro/blob/c4274b60033bf02f45d18b75c542e66a1c62253e/lib/default_day_tile.dart#L19

**Comment by billy124** [comment]
Hey, please can you tell me how you have added scroll in months view?

**Comment by SwissCheese5** [comment]
@adamstyrc You are correct. I was not setting the selection during the widget's build, i was only setting it during actual selection. Closed.

@billy124 The range I selected goes over a month, Calendarro automatically adds pages.

**Comment by adamstyrc** [comment]
@billy124 <https://github.com/billy124> The scroll is added with usage of
Flutter PageView :
https://api.flutter.dev/flutter/widgets/PageView-class.html
