### ISSUE TITLE
Conflict with material.dart import causes app run to fail

### ISSUE THREAD

**Issue by JoelOvien** [adamstyrc/calendarro#52]
Launching lib/main.dart on TECNO AX8 in debug mode...
 lib/main.dart
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:calendarro

For solutions, see https://dart.dev/go/unsound-null-safety
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:53:19: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      startDate = DateUtils.getFirstDayOfCurrentMonth();
                  ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:55:17: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
    startDate = DateUtils.toMidnight(startDate);
                ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:58:17: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      endDate = DateUtils.getLastDayOfCurrentMonth();
                ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:60:15: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
    endDate = DateUtils.toMidnight(endDate);
              ^^^^^^^^^

../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:81:41: Error: Method not found: 'TypeMatcher'.
      context.ancestorStateOfType(const TypeMatcher<CalendarroState>());
                                        ^^^^^^^^^^^

../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:81:15: Error: The method 'ancestorStateOfType' isn't defined for the class 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorStateOfType'.
      context.ancestorStateOfType(const TypeMatcher<CalendarroState>());
              ^^^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:106:25: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
            .difference(DateUtils.toMidnight(startDate))
                        ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:178:20: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      pagesCount = DateUtils.calculateMonthsDifference(
                   ^^^^^^^^^

../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:201:28: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      var maxWeeksNumber = DateUtils.calculateMaxWeeksNumberMonthly(
                           ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:216:16: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
        return DateUtils.isSameDay(selectedSingleDate, date);
               ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:220:13: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
            DateUtils.isSameDay(currentDate, date),
            ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:231:20: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.

            return DateUtils.isSameDay(selectedDates[0], date);
                   ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:235:20: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
            return DateUtils.isSameDay(date, selectedDates[0])
                   ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:236:18: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.

              || DateUtils.isSameDay(date, selectedDates[1])
                 ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:246:13: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
        if (DateUtils.isSameDay(selectedDates[i], date)) {

            ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:304:30: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.

        var lastDayOfMonth = DateUtils.getLastDayOfMonth(widget.startDate);
                             ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:308:23: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      pageStartDate = DateUtils.getFirstDayOfMonth(widget.endDate);
                      ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:311:42: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      DateTime firstDateOfCurrentMonth = DateUtils.addMonths(
                                         ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:315:21: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      pageEndDate = DateUtils.getLastDayOfMonth(firstDateOfCurrentMonth);
                    ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:328:11: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
          DateUtils.addDaysToDate(widget.startDate, 6 - widget.startDayOffset);
          ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:330:23: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      pageStartDate = DateUtils.addDaysToDate(
                      ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:334:23: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      pageStartDate = DateUtils.addDaysToDate(
                      ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:336:21: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
      pageEndDate = DateUtils.addDaysToDate(
                    ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro.dart:367:9: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
        DateUtils.isSameDay(currentDate, date),
        ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro_page.dart:28:31: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
    DateTime rowLastDayDate = DateUtils.addDaysToDate(pageStartDate, 6 - startDayOffset);
                              ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro_page.dart:35:13: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
            DateUtils.addDaysToDate(pageStartDate, 7 * i - startDayOffset);
            ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/calendarro_page.dart:42:13: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
            DateUtils.addDaysToDate(pageStartDate, 7 * i - startDayOffset + 6);
            ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/default_day_tile.dart:14:22: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
    bool isWeekend = DateUtils.isWeekend(date);
                     ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/calendarro-1.2.0/lib/default_day_tile.dart:16:20: Error: 'DateUtils' is imported from both 'package:calendarro/date_utils.dart' and 'package:flutter/src/material/date.dart'.
    bool isToday = DateUtils.isToday(date);
                   ^^^^^^^^^

FAILURE: Build failed with an exception.
* Where:
Script '/home/joel/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/joel/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by wmfadel** [comment]
Is there any updates on this problem?

**Comment by JoelOvien** [comment]
I do not know if the issue was fixed by the owner but someone made a pull request with the fix and so I referenced his version of the git repo in my pubspec.yaml file


  calendarro:
    git:
      url: https://github.com/GiddyCode/calendarro.git
      ref: master
