### ISSUE TITLE
Request to Add Product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [adamstyrc/calendarro#9]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website. 

Looking forward to hear from you.

**Comment by adamstyrc** [comment]
Hi Maheshwari,

That's sounds great as the product is just to serve other developers :)
Feel free to publish it on your website, a mention about author sounds nice.
Let me know if you need anything adjusted before publishing ;)

Cheers!
